---
title: "Data Visualisation for Research"
subtitle: "Part 2: "
author: "Thomas Wise"
output: 
  ioslides_presentation:
  incremental: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

## Session Objectives and Transferable Skills

<div style="float: left; width: 50%;">
- To embed good practice, through creating replicatable graphics
- To be able to effectively combine complex plots retaining good practice
- To be able to generate publishable plots, in line with common requirements 
</div>
<div style="float: right; width: 50%;">
- Use of replicatable techniques for graph production 
- Use of effective layering techniques in ggplot
- Understanding techniques to make effective publishable plots in line with common standards.
</div>

## Schedule 

- Introduction (5 minutes)
- Review and Recap (5 minutes)
- Part 1: (35 minutes)
    - Advanced Plots (Multiple Layered geom's)
    - Advanced Customization (Legends, Breaks)
- Break (5 minutes)
- Part 2: (35 minutes)
    - Advanced Customization (Colours)
    - Saving, Publishing and Exporting Plots
- Review and Conclusion (5 minutes)


# Last Session Review

# Part 1

## 